timeout: 25m

options:
  machineType: E2_HIGHCPU_32

  # This build needs to run in environments where the _GITHUB_DEPLOY_KEY_SRC
  # substitution is defined, but also environments where it isn't. The
  # ALLOW_LOOSE option disables GCBs strict checking of substitution usage,
  # so that the build will still run if _GITHUB_DEPLOY_KEY_SRC is not defined.
  substitution_option: ALLOW_LOOSE

steps:
  # Run the integration tests. Actual content of this job depends on the changes
  # detected in the PR
  - name: us-west2-docker.pkg.dev/ci-account/teleport-dev/buildbox-kind:teleport10
    id: run-tests
    dir: /workspace/.cloudbuild/scripts
    entrypoint: bash
    args:
      - -xeuc
      - | 
        export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

        curl -LO "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        mv ./kubectl /usr/local/bin

        curl -LO https://github.com/k3s-io/k3s/releases/download/v1.23.6+k3s1/k3s 
        chmod +x ./k3s
        mv ./k3s /usr/local/bin

        echo Starting k3s...
        k3s server &
        until [ -f $$KUBECONFIG ]
        do
          sleep 5
        done

        echo Kube Config created, hopefully k3s is up

        echo Configuring service account
        TELEPORT_NAMESPACE="ci-teleport" /workspace/examples/k8s-auth/get-kubeconfig.sh

        echo Configuring test roles
        kubectl create -f /workspace/fixtures/ci-teleport-rbac/ci-teleport.yaml

        echo tidying up
        kubectl delete clusterrole/teleport-role
        kubectl delete clusterrolebinding/teleport-crb

        export KUBECONFIG=$$PWD/kubeconfig

        go run ./cmd/integration-tests          \
          -target "$_BASE_BRANCH"               \
          -bucket test-logs                     \
          -build "$BUILD_ID"                    \
          -key-secret "$_GITHUB_DEPLOY_KEY_SRC" \
          -a "test-logs/*.json"

    timeout: 25m
    env:
      - KUBECONFIG=/tmp/$BUILD_ID.kubeconfig

